services:
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-artisan_market}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  mongodb:
    image: mongodb/mongodb-community-server:latest
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB:-artisan_market}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    env_file:
      - .env

  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - "${NEO4J_HTTP_PORT:-7474}:7474"
      - "${NEO4J_BOLT_PORT:-7687}:7687"
    volumes:
      - neo4j_data:/data
    env_file:
      - .env

volumes:
  postgres_data:
  mongo_data:
  redis_data:
  neo4j_data: